name: Trace Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator make g++

    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Build your source files
      run: |
        git clone https://gitee.com/hitsz-cslab/cdp-tests.git
        rm cdp-tests/mySoC/*
        cp src/* cdp-tests/mySoC/
        cd cdp-tests
        make

    - name: Run run_all_tests.py
      run: |
        cd cdp-tests
        python3 run_all_tests.py

    - name: Export Waveforms
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: waveform.zip
        path: |
          cdp-tests/waveform/
